<h1> Branching and Looping

1. Guess a number game. The computer picks a random number from 1 to 5, the player tries to guess. The player may have the flexibility to enter the number in an expression format.

In [2]:

import numpy as np
comp_number = np.random.randint(1, 6)
player_num = eval(input("Enter your guess (you can use expressions): "))

while(comp_number != player_num):
    print("Wrong Guess!!")
    player_num = eval(input("Enter your guess again: "))
else:
    print("YAYY!! you guessed it right, the number was {}".format(comp_number))


Enter your guess (you can use expressions): 5
Wrong Guess!!
Enter your guess again: 1
Wrong Guess!!
Enter your guess again: 3
Wrong Guess!!
Enter your guess again: 0
Wrong Guess!!
Enter your guess again: 2
Wrong Guess!!
Enter your guess again: 6
Wrong Guess!!
Enter your guess again: 5
Wrong Guess!!
Enter your guess again: 5
Wrong Guess!!
Enter your guess again: 6
Wrong Guess!!
Enter your guess again: 4
YAYY!! you guessed it right, the number was 4


Kids Multiplication Table.

 Write a multiplication game program for kids. The program should give the player ten randomly generated multiplication questions to do. After each, the program should tell them whether they got it right or wrong and what the correct answer is.

In [3]:
score = 0
for i in range(10):
    num1, num2 = np.random.randint(1, 10, 2)

    ans = int(input("{} X {} = ".format(num1, num2)))
    if num1*num2 == ans:
        print("correct!!")
        score += 1
    else:
        print("wrong, the correct ans is", num1*num2)
        score -= 0.5

print("your final score is: {}/10".format(score))


6 X 5 = 30
correct!!
4 X 1 = 4
correct!!
1 X 6 = 8
wrong, the correct ans is 6
4 X 3 = 11
wrong, the correct ans is 12
9 X 1 = 9
correct!!
2 X 5 = 10
correct!!
7 X 8 = 56
correct!!
8 X 4 = 32
correct!!
4 X 7 = 28
correct!!
6 X 3 = 17
wrong, the correct ans is 18
your final score is: 5.5/10


Check a list contains even number or not

numbers = [11,33,55,39,55,75,37,21,23,41,13]

In [4]:
num = [11,33,55,39,55,75,37,21,23,41,13]
flag = 0
for i in num:
    if i%2 == 0:
        flag = 1
        break
if flag == 0:
    print("no even")
else:
    print("contains even")

no even


Read N and generate the Fibonacci sequence upto N

In [5]:
N = int(input("N: "))
a, b = 0, 1
print(a, b, end=" ")
for _ in range(N-2):
    a, b = b, a + b
    print(b, end=" ")

N: 10
0 1 1 2 3 5 8 13 21 34 

Use a for loop to print a box like the one below. Allow the user to specify how wide and how
high the box should be.

In [6]:
h = int(input("height: "))
w = int(input("wide: "))

print("* " * w)
for i in range(h-2):
    print("* ", end = "")
    print("  " * (w-2), end = "")
    print("* ")
print("* " * w)

height: 5
wide: 7
* * * * * * * 
*           * 
*           * 
*           * 
* * * * * * * 


Use for loops to print a diamond like the one below. Allow the user to specify how high the diamond should be.


In [7]:
h = int(input())
for i in range(h):
     print(" " * (h - i - 1) + "* " * (i + 1))
for i in range(h-1, 0, -1 ):
    print(" "*(h - i)+ "* " * (i))

7
      * 
     * * 
    * * * 
   * * * * 
  * * * * * 
 * * * * * * 
* * * * * * * 
 * * * * * * 
  * * * * * 
   * * * * 
    * * * 
     * * 
      * 


Write a program that lets the user play Rock-Paper-Scissors against the computer. There should be five rounds, and after those five rounds, your program should print out who won and lost or that there is a tie.

In [8]:
import random

choices = ["rock", "paper", "scissors"]
user_score = 0
comp_score = 0

print("Welcome to Rock-Paper-Scissors! Best of 5 rounds.\n")

for round_num in range(1, 6):
    print(f"Round {round_num}:")
    user_choice = input("Enter rock, paper, or scissors: ").lower()

    # ensure valid input
    while user_choice not in choices:
        user_choice = input("Invalid choice! Enter rock, paper, or scissors: ").lower()

    comp_choice = random.choice(choices)
    print(f"Computer chose: {comp_choice}")

    if user_choice == comp_choice:
        print("It's a tie!\n")
    elif (user_choice == "rock" and comp_choice == "scissors") or \
         (user_choice == "scissors" and comp_choice == "paper") or \
         (user_choice == "paper" and comp_choice == "rock"):
        print("You win this round!\n")
        user_score += 1
    else:
        print("Computer wins this round!\n")
        comp_score += 1

# final result
print("Final Results:")
print(f"You: {user_score} | Computer: {comp_score}")

if user_score > comp_score:
    print(" You won the game!")
elif user_score < comp_score:
    print(" Computer won the game!")
else:
    print("It's a tie overall!")


Welcome to Rock-Paper-Scissors! Best of 5 rounds.

Round 1:
Enter rock, paper, or scissors: paper
Computer chose: paper
It's a tie!

Round 2:
Enter rock, paper, or scissors: rock
Computer chose: scissors
You win this round!

Round 3:
Enter rock, paper, or scissors: rock
Computer chose: paper
Computer wins this round!

Round 4:
Enter rock, paper, or scissors: rock
Computer chose: scissors
You win this round!

Round 5:
Enter rock, paper, or scissors: paper
Computer chose: rock
You win this round!

Final Results:
You: 3 | Computer: 1
 You won the game!


<h2> Playing with Magic Words
<h3>Here a word ‘S’ of length ‘n’ is said to be magic word if it satisfies the following conditions:
All letters of S are lowercase letters of the English alphabets.
Si, the character in the ith position, is lexicographically smaller than Sn-1-i for all even i from 0 to
n/2
Si is lexicographically greater than Sn-1-i for all odd i from 0 to n/2
For example, the word “difference” is a magic word, while “similar” is not.
Given a word, write python code to check whether the word is magic or not.

In [9]:
word = list(input("your word: "))
n = len(word)
is_magic = True

for i in range(n // 2):
    if i % 2 == 0:    #even
        if not (word[i] < word[n-1-i]):
            is_magic = False
            break
    else:       #odd
        if not (word[i] > word[n-1-i]):
            is_magic = False
            break

if is_magic:
    print("Magic word")
else:
    print("Not a magic word")


your word: difference
Magic word


<h1> Programs on Looping Control Structure

Write a Python program that will print your name 10 times

In [10]:
print("Soham " *10)

Soham Soham Soham Soham Soham Soham Soham Soham Soham Soham 


Write a Python program that will print 1 2 3 4 5 6 7 8 9 10

In [11]:
for i in range(1,10+1):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

Write a Python program that will print the number between m and n

In [12]:
m=int(input("m:"))
n=int(input("n:"))
for i in range(m,n+1):
  print(i,end=" ")

m:4
n:12
4 5 6 7 8 9 10 11 12 

Write a Python program that will print all odd number between m and n


In [13]:
m=int(input("m:"))
n=int(input("n:"))
for i in range(m,n+1):
  if i%2!=0:
    print(i,end=" ")

m:56
n:89
57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 

Write a Python program that will print 9 7 5 3 1 -1 -3 -5 -7 -9

In [14]:
for i in range(9,-11,-2):
  print(i,end=" ")

9 7 5 3 1 -1 -3 -5 -7 -9 

Write a Python program that will print sum of the following series Sum = 1+ 1⁄2 + 1/3 + .....1/n

In [15]:
n = int(input("n: "))
sum = 0
for i in range(1, n+1):
  sum += 1 / i
print(sum)

n: 9
2.8289682539682537


Write a Python program that will print sum of the following series Sum = 1+ 1⁄2! + 1/3! + .....1/n!


In [17]:
def fact(n):
    factorial = 1
    for i in range(1, n+1):
        factorial*=i
    return factorial
sum = 0
n = int(input("n: "))
for i in range (1,n+1):
    sum += 1/fact(i)
print(sum)

n: 9
1.7182815255731925


Write a Python program that will print sum of the following series e^x = 1+ x + x^2/2! +x^3/3! .....x^n/n!


In [18]:
def fact(n):
    factorial = 1
    for i in range(1, n+1):
        factorial*=i
    return factorial

sum = 1
n = int(input("n: "))
x = int(input("x: "))
for i in range (1,n+1):
    sum += (x**i)/fact(i)

print("e^",x," is: ", sum)

n: 9
x: 5
e^ 5  is:  143.68945656966488


Write a Python program that will read x and compute sin(x)

In [19]:
def fact(n):
    factorial = 1
    for i in range(1, n+1):
        factorial *= i
    return factorial

x = float(input("x (in radians): "))
n_terms = int(input("Number of terms: "))  # how many terms of the series to use
sinex = 0

for i in range(n_terms):
    sinex += ((-1)**i * x**(2*i + 1)) / fact(2*i + 1)

print(f"sin({x}) ≈ {sinex}")

x (in radians): 1.5
Number of terms: 9
sin(1.5) ≈ 0.9974949866040727


Write a Python program that will check the number is prime or composite.

In [20]:
n = int(input("num to check: "))

for i in range(2, n//2):
    if n%i == 0:
        print("composite")
        break
else:
    print("prime")

num to check: 5
prime


Write a Python program that will read two integers and compute GCD and LCM

In [21]:
import math

num1 = int(input("number 1: "))
num2 = int(input("number 2: "))
gcd = math.gcd(num1, num2)
lcm = math.lcm(num1, num2)
print("GCD is: ", gcd)
print("LCM is: ", lcm)


number 1: 45
number 2: 60
GCD is:  15
LCM is:  180


Write a Python program that read an integer and print the number of digit.

In [22]:
num = int(input("number in integer:  "))

print("number of digits: ", len(list(str(num))))

number in integer:  456456
number of digits:  6


Write a Python program that will read a number and compute sum of the digit

In [1]:
num = int(input("number: "))
total_sum = 0
for i in str(num):
    total_sum += int(i)
print("Sum of digits:", total_sum)

number: 3445
Sum of digits: 16


Write a Python program that will reverse an integer

In [2]:
num = int(input("number: "))
l1 = list(str(num))
l1.reverse()
l2 = ''.join(l1)
print(int(l2))

number: 5432
2345


Write a Python program that will check a number is palindrome or not.

In [3]:
num = int(input("number: "))
l1 = list(str(num))
l1.reverse()
l2 = ''.join(l1)
if num == int(l2):
    print('palindrome')
else:
    print("not a palindrome")

number: 1234321
palindrome


Write a python program to find the Fibonacci series up to nth term.

In [4]:
n = int(input("no many terms: "))

a, b = 0, 1
for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b

no many terms: 19
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 

Write a Python program to check the number is Armstrong or not. For example, 371 is an Armstrong number since 3 * 3 * 3 + 7 * 7 * 7 + 1 *1 * 1 = 371.


In [5]:
num = int(input("number: "))
l1 = list(str(num))
sum = 0
for i in l1:
    sum += int(i)**len(l1)
if sum == num:
    print("Armstrong")
else:
    print("not a armstrong")



number: 12344
not a armstrong


Write a Python program that will display the prime’s number between M and N.

In [6]:
import math

def is_prime(num):
    for i in range(2, int(math.sqrt(num))+1):
        if num % i == 0:
            return 0
    else:
        return 1

M = int(input("lower bound: "))
N = int(input("upper bound: "))

for i in range(M, N+1):
    if is_prime(i) == 1:
        print(i, end = " ")

lower bound: 4
upper bound: 78
5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 

Write a python program that will take a positive integer (num say) as input and displaythe positive numbers, which are less than num and relatively prime to num.


In [7]:
import math

num = int(input("Enter a positive integer: "))

print(f"Numbers less than {num} that are relatively prime to {num}:")
for i in range(1, num):
    if math.gcd(i, num) == 1:
        print(i, end=" ")

Enter a positive integer: 24
Numbers less than 24 that are relatively prime to 24:
1 5 7 11 13 17 19 23 

<h2>Write python programs that will print the following output.

1\
1 2\
1 2 3\
1 2 3 4


In [ ]:
n = int(input("height: "))
for i in range(1,n+1):
    for j in range(1, i+1):
        print(j, end = " ")
    print()

height: 4
1 
1 2 
1 2 3 
1 2 3 4 



1\
2 2\
3 3 3\
4 4 4 4

In [ ]:
n = int(input("height: "))
for i in range(1,n+1):
    for j in range(1, i+1):
        print(i, end = " ")
    print()

height: 4
1 
2 2 
3 3 3 
4 4 4 4 


A A A A A A\
A ______ A\
A_______ A\
A_______ A\
A A A A A A

In [ ]:
height = int(input("height: "))
width = int(input("width: "))

print("A " * width)
for i in range(1, height+1 -2):
    print("A " + "  " * (width -2) + "A ")
print("A " * width)

height: 10
width: 15
A A A A A A A A A A A A A A A 
A                           A 
A                           A 
A                           A 
A                           A 
A                           A 
A                           A 
A                           A 
A                           A 
A A A A A A A A A A A A A A A 



a\
a b\
a b c

In [ ]:
n = int(input("height: "))
j = 97
for i in range(1, n+1):
    for j in range(97, 97+i):
        print(chr(j), end = " ")
    print()

height: 3
a 
a b 
a b c 


aaaaaa\
aaaaa\
aaaa\
aaa\
aa\
a\

In [ ]:
n = int(input("height: "))

for i in range(1, n+1):
    print("  "* i + "a "*(n-i+1))

height: 5
  a a a a a 
    a a a a 
      a a a 
        a a 
          a 


In [9]:
n = int(input("height: "))

for i in range(1, n+1):
    print("  " * (n-i) + "* "*(2*i -1))


height: 7
            * 
          * * * 
        * * * * * 
      * * * * * * * 
    * * * * * * * * * 
  * * * * * * * * * * * 
* * * * * * * * * * * * * 


In [14]:
n = int(input("height: "))

for i in range(1, n+1):
    print("  " * (n - i), end=" ")

    for j in range(i):
        print(i + j, end=" ")

    for j in range(i - 2, -1, -1):
        print(i + j, end=" ")
    print()


height: 4
       1 
     2 3 2 
   3 4 5 4 3 
 4 5 6 7 6 5 4 


In [15]:
n = int(input("height:  "))

for i in range(n):
    print("  " * (n - i - 1), end="")

    num = 1
    for j in range(i + 1):
        print(num, end="   ")
        num = num * (i - j) // (j + 1)

    print()

height:  6
          1   
        1   1   
      1   2   1   
    1   3   3   1   
  1   4   6   4   1   
1   5   10   10   5   1   


<h1> Numpy Exercises

In [17]:
import numpy as np

In [18]:
#Create a null vector of size 10 but the fifth value is 1


l1 = np.zeros(10)
l1[4] = 1
l1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [19]:
#Create a vector with values ranging from 10 to 49


l1 = np.arange(10,50)
l1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
#Reverse a vector (first element becomes last)


l2 = l1[::-1]
l2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [21]:
#Create a 3x3 matrix with values ranging from 0 to 8


l3 = np.arange(0,8+1).reshape(3,3)
l3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
#Find indices of non-zero elements from [1,2,0,0,4,0]



l4 = [1,2,0,0,4,0]
l5 = np.array(l4)
np.nonzero(l5)[0]

array([0, 1, 4])

In [23]:
#Create a 3x3x3 array with random values



from numpy import random

l6 = random.randint(100, size=(27)).reshape(3,3,3)
l6

array([[[81, 61, 68],
        [53, 38, 90],
        [29, 42, 50]],

       [[12,  7, 48],
        [28, 92, 57],
        [21, 33,  8]],

       [[ 7, 97, 92],
        [27, 38, 26],
        [41, 51, 22]]])

In [24]:
#Create a 10x10 array with random values and find the minimum and
#maximum values.


from numpy import random

l7 = random.randint(1000,  size=(10,10))
print(l7)
print()
print("min {} at {}".format( l7.min(),  l7.argmin()))
print("max {} at {}".format( l7.max(), l7.argmax()))


[[273 817 653 634 661 868 260  83 618 775]
 [164 246 272 119  70 232 835 459 814 605]
 [144 228 330 704 713 431 995 378 670 449]
 [ 98 128 927 259 118 803 636 183 963 806]
 [670 492 440 224 688 377 393  77 626 678]
 [471 875 791 226 264 620 764 985 601 906]
 [670 509 989 757 688 442 301 595 124 743]
 [838 926 760 779 981 373 746 744 714 232]
 [575 134  26 514 462 212 637  54  15 981]
 [ 68 517 903 946 464 475 871 510 817 796]]

min 15 at 88
max 995 at 26


In [25]:
#Create a random vector of size 30 and find the mean value


from numpy import random

l8 = random.randint(1000,  size=(30)).mean()
print(l8)

497.76666666666665


In [26]:
# Create a 2d array with 1 on the border and 0 inside



l9 = np.ones(25).reshape(5,5)
l9[ 1:4, 1:4] = 0
l9

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
#Normalize a 5x5 random matrix


l10 = np.random.randint(10000, size=(5,5))
normalized_l10 = (l10 - l10.mean()) / l10.std()
print(normalized_l10)

[[ 1.18376044 -0.80750537  0.88378643 -1.60127221 -1.08761809]
 [-0.15276758 -0.39726695  1.29881896  0.22665159  0.72626584]
 [ 1.31388615 -0.33220409 -1.16055697  1.06767461 -0.6198504 ]
 [-0.53115945  1.74398587 -1.02221279  1.24711111 -1.35677285]
 [-1.2348656   0.79064382  0.76941278 -0.86640438 -0.08154088]]


In [28]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)



l11 = np.random.randint(100, size = (5,3))
l12 = np.random.randint(100, size = (3,2))

l13 = np.dot(l11,l12)
l13

array([[ 7514, 13360],
       [11109, 13964],
       [12399, 13976],
       [ 9827, 12552],
       [11727, 12312]])

In [29]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.

l14 = np.arange(10,30)
print(l14)
x = [int(l14[i]) for i in range(len(l14)) if (i <3 or i >8)]
print(x)
y = np.delete(l14,  np.arange(3, 9))
print(y)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10, 11, 12, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[10 11 12 19 20 21 22 23 24 25 26 27 28 29]


In [30]:
#Find the eigenvalues and eigenvectors of a square matrix.

l15 = np.random.randint(0,3, size  = (5,5))
print(l15)

eigenvalues, eigenvectors = np.linalg.eig(l15)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors :")
print(eigenvectors)

[[1 0 2 1 2]
 [2 1 1 0 0]
 [2 2 1 2 1]
 [1 2 2 0 2]
 [0 2 0 0 1]]
Eigenvalues:
[ 5.45038663+0.j         -0.0075146 +1.83659263j -0.0075146 -1.83659263j
  0.28461668+0.j         -1.71997411+0.j        ]

Eigenvectors :
[[-0.46324503+0.j          0.57271851+0.j          0.57271851-0.j
   0.38490022+0.j         -0.30640572+0.j        ]
 [-0.34849653+0.j         -0.2960738 -0.46522954j -0.2960738 +0.46522954j
  -0.21571995+0.j         -0.03507042+0.j        ]
 [-0.62445426+0.j          0.00729881-0.07504141j  0.00729881+0.07504141j
  -0.61547798+0.j          0.70820208+0.j        ]
 [-0.49948286+0.j         -0.08467509+0.27900175j -0.08467509-0.27900175j
  -0.25057349+0.j         -0.63456318+0.j        ]
 [-0.15661405+0.j         -0.25347239+0.46146582j -0.25347239-0.46146582j
   0.60308913+0.j          0.02578732+0.j        ]]


In [31]:
#Find the inverse of a square matrix.

l16 = np.random.randint(100, size = (5,5))
print(l16)

l17 = np.linalg.inv(l16)
print(l17)

[[55 25 76 18 40]
 [31 48 57 47 59]
 [16  4  7 40 91]
 [ 6 92 56 54 90]
 [35 93 92  5 57]]
[[-0.16329795  0.22089558  0.03843037 -0.17574824  0.10209223]
 [-0.10432141  0.12354299  0.01490577 -0.08963471  0.06306175]
 [ 0.15437368 -0.18481895 -0.03599461  0.14413466 -0.08714454]
 [ 0.00030589  0.02515652 -0.01089523  0.00633866 -0.01886813]
 [ 0.02128793 -0.04111021  0.01113476  0.02096727 -0.00572512]]


<h1> Pandas Exercises

In [34]:
import pandas as pd

In [35]:
data = {
'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills',
'spoonbills'],
'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4],
'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2], 'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [36]:
# Create a DataFrame birds from this dictionary data which has the index labels.

df = pd.DataFrame(data, index = labels)
df

birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      yes
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

In [37]:
#Display a summary of the basic information about birds DataFrame and its data.

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   birds     10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes


In [38]:
#Print the first 2 rows of the birds dataframe
df.head(2)

birds  age  visits priority
a  Cranes  3.5       2      yes
b  Cranes  4.0       4      yes

In [41]:
#Print all the rows with only 'birds' and 'age' columns from the dataframe
selected_cols=['birds', 'age']
print(df[selected_cols])


        birds  age
a      Cranes  3.5
b      Cranes  4.0
c     plovers  1.5
d  spoonbills  NaN
e  spoonbills  6.0
f      Cranes  3.0
g     plovers  5.5
h      Cranes  NaN
i  spoonbills  8.0
j  spoonbills  4.0


In [44]:
#select [2, 3, 7] rows and in columns ['birds', 'age', 'visits']


df.loc[['c','d','h'],['birds', 'age', 'visits']]

birds  age  visits
c     plovers  1.5       3
d  spoonbills  NaN       4
h      Cranes  NaN       2

In [45]:
#select the rows where the number of visits is less than 4


df[df['visits']<4]

birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

In [46]:
#select the rows with columns ['birds', 'visits'] where the age is missing i.e NaN

cols=['birds','visits']
df.loc[df['age'].isnull(),cols]
df[df['age'].isnull()][cols]

birds  visits
d  spoonbills       4
h      Cranes       2

In [47]:
#Select the rows where the birds is a Cranes and the age is less than 4


df[(df['birds']=='Cranes')&(df['age']<4)]

birds  age  visits priority
a  Cranes  3.5       2      yes
f  Cranes  3.0       4       no

In [48]:
#Select the rows the age is between 2 and 4(inclusive)


df[(df['age']>=2)&(df['age']<=4)]

birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
f      Cranes  3.0       4       no
j  spoonbills  4.0       2       no

In [49]:
#Find the total number of visits of the bird Cranes


int(df.groupby('birds')['visits'].sum()['Cranes'])

12

In [50]:
# Calculate the mean age for each different birds in dataframe.


df.groupby('birds')['age'].mean()

birds
Cranes        3.5
plovers       3.5
spoonbills    6.0
Name: age, dtype: float64

In [51]:
#Append a new row 'k' to dataframe with your choice of values for each column. Then delete
#that row to return the original DataFrame.


new_row=pd.DataFrame({'birds':['chicken'],'age':[1],'visits':[9999],'priority':['yes']},index=['k'])
df=pd.concat([df,new_row]).reset_index(drop=True)
df
df=df.drop([10,11,12],errors='ignore')
df

birds  age  visits priority
0      Cranes  3.5       2      yes
1      Cranes  4.0       4      yes
2     plovers  1.5       3       no
3  spoonbills  NaN       4      yes
4  spoonbills  6.0       3       no
5      Cranes  3.0       4       no
6     plovers  5.5       2       no
7      Cranes  NaN       2      yes
8  spoonbills  8.0       3       no
9  spoonbills  4.0       2       no

In [52]:
#Find the number of each type of birds in dataframe (Counts)


df['birds'].value_counts()

birds
Cranes        4
spoonbills    4
plovers       2
Name: count, dtype: int64

In [53]:
#Sort dataframe (birds) first by the values in the 'age' in decending order, then by the value in
#the 'visits' column in ascending order.


df.sort_values(by=['age','visits'],ascending=[False,True])

birds  age  visits priority
8  spoonbills  8.0       3       no
4  spoonbills  6.0       3       no
6     plovers  5.5       2       no
9  spoonbills  4.0       2       no
1      Cranes  4.0       4      yes
0      Cranes  3.5       2      yes
5      Cranes  3.0       4       no
2     plovers  1.5       3       no
7      Cranes  NaN       2      yes
3  spoonbills  NaN       4      yes

In [54]:
#Replace the priority column values with'yes' should be 1 and 'no' should be 0


df['priority']=df['priority'].map({'no':0,'yes':1})
df

birds  age  visits  priority
0      Cranes  3.5       2         1
1      Cranes  4.0       4         1
2     plovers  1.5       3         0
3  spoonbills  NaN       4         1
4  spoonbills  6.0       3         0
5      Cranes  3.0       4         0
6     plovers  5.5       2         0
7      Cranes  NaN       2         1
8  spoonbills  8.0       3         0
9  spoonbills  4.0       2         0

In [55]:
#In the 'birds' column, change the 'Cranes' entries to 'trumpeters'.


df['birds']=df['birds'].replace('Cranes','trumpeters')
df

birds  age  visits  priority
0  trumpeters  3.5       2         1
1  trumpeters  4.0       4         1
2     plovers  1.5       3         0
3  spoonbills  NaN       4         1
4  spoonbills  6.0       3         0
5  trumpeters  3.0       4         0
6     plovers  5.5       2         0
7  trumpeters  NaN       2         1
8  spoonbills  8.0       3         0
9  spoonbills  4.0       2         0